# Generated by Django 5.0.6 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(default=2, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
